twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    date:
        format: 'd/m/Y H:i'
        interval_format: '%d days'
        timezone: 'Europe/Paris'

when@test:
    twig:
        strict_variables: true
